name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run sh-checker
        uses: luizm/action-sh-checker@v0.9.0
        env:
          SHELLCHECK_OPTS: -s ash
          SHFMT_OPTS: -i 2
        with:
          sh_checker_comment: false
